### ISSUE TITLE
Failure to start game

### ISSUE THREAD

**Issue by Cringe6969** [TeamStarDrive/StarDrive#108]
After installing blackbox with the automatic patcher latest release - https://github.com/TeamStarDrive/StarDrive/releases/tag/mars-patch-1.41.14819 9I selected the stardrive installation folder in my steamapps/common directory) the game keep throwing this error:

(!) Exception: Game.Run() failed

Unable to load DLL 'SDNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Followed by: The type initializer for 'Ship_Game.Parallel' threw an exception.
Version = 1.41.14819 develop/commit
Mod = Vanilla
Language = English
StarDate = NULL
Ships = NULL
Planets = NULL
Memory = 666
XnaMemory = 0
Thread = Main Thread
ThreadId = 1
Thread #1 Main Thread StackTrace:
   at Ship_Game.Parallel.GetPhysicalCPUCoreCount()
   at Parallel.InitThreadPool() in Threading\Parallel.cs:line 328
   at Parallel..cctor() in Threading\Parallel.cs:line 320
Followed by:
   at StarDriveGame..ctor() in GameScreens\StarDriveGame.cs:line 36
   at Program.Main(String[] args) in GameScreens\Program.cs:line 215

Is there more to the installation that I'm missing?

**Comment by gkapulis** [comment]
please install the main release first - https://github.com/TeamStarDrive/StarDrive/releases/tag/mars-1.41.14664
make sure not to use programfiles dir or steam dir.  Follow the instructions in the link i added. Please update if it works for you.
