### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by DizzyIoeuy** [TeamStarDrive/StarDrive#129]
(!) Exception: Failed to load game data!

Required StarData file not found! /Goods/Goods.yaml
Version = 1.50.15004 main/commit
Mod = Vanilla
Language = English
StarDate = NULL
Ships = NULL
Planets = NULL
Memory = 5578
XnaMemory = 71
Thread = ParallelTask_3
ThreadId = 19
Thread #19 ParallelTask_3 StackTrace:
   at Data.Yaml.YamlParser.OpenStream(FileInfo f, String nameInfo) in Data\Yaml\YamlParser.cs:line 120
   at Data.Yaml.YamlParser..ctor(String modOrVanillaFile) in Data\Yaml\YamlParser.cs:line 26
   at Data.Yaml.YamlParser.DeserializeArray[T](String modOrVanillaFile) in Data\Yaml\YamlParser.cs:line 621
   at ResourceManager.LoadGoods() in Data\ResourceManager.cs:line 1248
   at ResourceManager.Profiled(String uniqueName, Action body) in Data\ResourceManager.cs:line 189
   at ResourceManager.Profiled(Action body) in Data\ResourceManager.cs:line 198
   at ResourceManager.LoadContent(Boolean loadShips) in Data\ResourceManager.cs:line 254
   at ResourceManager.LoadAllResources(ScreenManager manager, ModEntry mod) in Data\ResourceManager.cs:line 227
   at ResourceManager.LoadItAll(ScreenManager manager, ModEntry mod) in Data\ResourceManager.cs:line 165
   at GameLoadingScreen.LoadGameThread() in GameScreens\MainMenu\GameLoadingScreen.cs:line 161

Thread #1 Main Thread StackTrace:
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout)
   at GameLoadingScreen.LoadingFinished() in GameScreens\MainMenu\GameLoadingScreen.cs:line 108
   at GameLoadingScreen.HandleInput(InputState input) in GameScreens\MainMenu\GameLoadingScreen.cs:line 103
   at ScreenManager.Update(UpdateTimes elapsed) in GameScreens\ScreenManager.cs:line 681
   at GameBase.UpdateGame(Single deltaTime) in GameScreens\GameBase.cs:line 229
   at StarDriveGame.Update(Single deltaTime) in GameScreens\StarDriveGame.cs:line 142
   at XNA.Game.Tick() in ts\BlackBox\XNA.Game\Game.cs:line 250
   at XNA.Game.HostIdle(Object sender, EventArgs e) in ts\BlackBox\XNA.Game\Game.cs:line 488
   at XNA.GameHost.OnIdle() in ts\BlackBox\XNA.Game\GameHost.cs:line 55
   at XNA.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e) in ts\BlackBox\XNA.Game\WindowsGameHost.cs:line 73
   at XNA.WindowsGameHost.Run() in ts\BlackBox\XNA.Game\WindowsGameHost.cs:line 87
   at XNA.Game.Run() in ts\BlackBox\XNA.Game\Game.cs:line 157
   at Program.Main(String[] args) in GameScreens\Program.cs:line 217

**Comment by RedFox20** [comment]
Reinstall 1.50
