### ISSUE TITLE
Do you have a Plan to add supporting a Linux version? 

### ISSUE THREAD

**Issue by EndrII** [TeamStarDrive/StarDrive#139]
Hi. These project have plans to add support Linux version ?

**Comment by EndrII** [comment]
I was tried it using wine but it failed. 
```
(!) Exception: Game.Run() failed
Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Version = 1.50.15010 main/commit
Mod = Vanilla
Language = English
StarDate = NULL
Ships = NULL
Planets = NULL
Memory = 740
XnaMemory = 0
Thread = 
ThreadId = 1
Thread #1  StackTrace:
   at Ship_Game.Data.Serialization.TypeSerializerMap.Get(Type type)
   at Data.Serialization.Types.ByteArraySerializer..ctor(TypeSerializerMap typeMap) in Data\Serialization\Types\ByteArraySerializer.cs:line 16
   at Data.Serialization.TypeSerializerMap..ctor() in Data\Serialization\TypeSerializerMap.cs:line 62
   at Data.YamlSerializer.YamlSerializer.YamlTypeMap..ctor() in Data\YamlSerializer\YamlSerializer.cs:line 32
   at Data.YamlSerializer.YamlSerializer..ctor(Type type) in Data\YamlSerializer\YamlSerializer.cs:line 20
   at Data.Yaml.YamlParser.DeserializeOne[T]() in Data\Yaml\YamlParser.cs:line 646
   at Data.Yaml.YamlParser.DeserializeOne[T](FileInfo file) in Data\Yaml\YamlParser.cs:line 663
   at GamePlayGlobals.Deserialize(FileInfo globalsFile) in GamePlayGlobals.cs:line 137
   at GlobalStats.LoadModInfo(String modPath) in GlobalStats.cs:line 367
   at GlobalStats.LoadConfig() in GlobalStats.cs:line 354
   at Program.Main(String[] args) in GameScreens\Program.cs:line 204

```

**Comment by SmischenkoB** [comment]
we would like to add 64 bit support first

**Comment by SmischenkoB** [comment]
Any support with development is appreciated)

**Comment by EndrII** [comment]
> Did you clean install this 1.50 version?

I installed clean 1.50 and after this install last patch

**Comment by SmischenkoB** [comment]
So you launched game successfully at least once?

**Comment by SmischenkoB** [comment]
communication is much easier on discord of the project - https://discord.com/invite/dfvnfH4

**Comment by EndrII** [comment]
> So you launched game successfully at least once?

No) 
probably I will try to prepare environment for this game later, please describe list of all dependencies with versions. 
for example: 
Net 4.5 ...

When my work will be finished successful, I will try to prepare local snap distribution of this game.
It will be like a https://snapcraft.io/tmnationsforever. But I will not publish this game on the store. (publication will discuss with main developers)

**Comment by SmischenkoB** [comment]
.net framework 4.8, c++ MSVC v143  - if not enough - check How do I get set up for Development? section in readme

**Comment by SmischenkoB** [comment]
Here is linux guide from steam - https://steamcommunity.com/sharedfiles/filedetails/?id=2814045973
