### ISSUE TITLE
NEW BUG Blackbox+Combined Arms

### ISSUE THREAD

**Issue by Th3Protagonist** [TeamStarDrive/StarDrive#158]
I literally played this game for 9 hours straight, with no issue, and multiple reloads.  Now, today, i am plagued by a new error keeping from loading ANY of my saves.  Please assist. The latest version of blackbox and combined arms are the only mods in use.

(!) Exception: LoadUniverseScreen failed: C:\Users\thepr\AppData\Roaming\StarDrive\Saved Games\Dauntless Corporation, Star Date 1106.1.sav

Unable to read beyond the end of the stream.
Version = 1.50.15019 main/commit
Mod = Combined Arms
ModVersion = v8.5e
Language = English
StarDate = NULL
Ships = NULL
Planets = NULL
Memory = 136686
XnaMemory = 144159
Thread = ParallelTask_1
ThreadId = 18
Thread #18 ParallelTask_1 StackTrace:
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at Data.Binary.BinarySerializerHeader..ctor(Reader reader) in Data\Binary\BinarySerializerHeader.cs:line 42
   at Data.Binary.BinarySerializer.Deserialize(Reader reader, Boolean verbose) in Data\Binary\BinarySerializer.cs:line 89
   at Data.Binary.BinarySerializer.DeserializeMultiType(Reader reader, Type[] types, Boolean verbose) in Data\Binary\BinarySerializer.cs:line 148
   at SavedGame.Deserialize(FileInfo saveFile, Boolean verbose) in SavedGame.cs:line 107
   at GameScreens.LoadGame.LoadGame.DecompressSaveGame(FileInfo file, ProgressCounter step) in GameScreens\LoadGame\LoadGame.cs:line 116
   at GameScreens.LoadGame.LoadGame.Load(Boolean noErrorDialogs, Boolean startSimThread) in GameScreens\LoadGame\LoadGame.cs:line 54

Thread #1 Main Thread StackTrace:
   at System.Reflection.Emit.ModuleBuilder.GetMemberRefOfMethodInfo(RuntimeModule module, Int32 tr, IRuntimeMethodInfo method)
   at System.Reflection.Emit.ModuleBuilder.GetMemberRefOfMethodInfo(Int32 tr, RuntimeMethodInfo method)
   at System.Reflection.Emit.ModuleBuilder.GetMethodTokenNoLock(MethodInfo method, Boolean getGenericTypeDefinition)
   at System.Reflection.Emit.ModuleBuilder.GetMethodTokenInternal(MethodInfo method)
   at System.Reflection.Emit.ModuleBuilder.GetMethodTokenInternal(MethodBase method, IEnumerable`1 optionalParameterTypes, Boolean useMethodDef)
   at System.Reflection.Emit.ILGenerator.GetMethodToken(MethodBase method, Type[] optionalParameterTypes, Boolean useMethodDef)
   at System.Reflection.Emit.ILGenerator.EmitCall(OpCode opcode, MethodInfo methodInfo, Type[] optionalParameterTypes)
   at System.Reflection.Emit.ILGenerator.Emit(OpCode opcode, MethodInfo meth)
   at System.Xml.Serialization.CodeGenerator.Call(MethodInfo methodInfo)
   at System.Xml.Serialization.XmlSerializationReaderILGen.WriteXmlNodeEqual(String source, String name, String ns, Boolean doAndIf)
   at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(Member[] members, Member anyElement, String elementElseString)
   at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(Member[] members, String elementElseString, String elseString, Member anyElement, Member anyText)
   at System.Xml.Serialization.XmlSerializationReaderILGen.WriteArray(String source, String arrayName, ArrayMapping arrayMapping, Boolean readOnly, Boolean isNullable, Int32 fixupIndex, Int32 elementIndex)
   at System.Xml.Serialization.XmlSerializationReaderILGen.WriteElement(String source, String arrayName, String choiceSource, ElementAccessor element, ChoiceIdentifierAccessor choice, String checkSpecified, Boolean checkForNull, Boolean readOnly, Int32 fixupIndex, Int32 elementIndex)
   at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(Member[] members, Member anyElement, String elementElseString)
   at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(Member[] members, String elementElseString, String elseString, Member anyElement, Member anyText)
   at System.Xml.Serialization.XmlSerializationReaderILGen.GenerateTypeElement(XmlTypeMapping xmlTypeMapping)
   at System.Xml.Serialization.XmlSerializationReaderILGen.GenerateElement(XmlMapping xmlMapping)
   at System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at ResourceManager.TryDeserialize[T](String file) in Data\ResourceManager.cs:line 465
   at ResourceManager.LoadRandomAdvice(RandomBase random) in Data\ResourceManager.cs:line 973
   at LoadUniverseScreen.LoadContent() in GameScreens\LoadGame\LoadUniverseScreen.cs:line 30
   at GameScreen.InvokeLoadContent() in GameScreens\GameScreen.cs:line 284
   at ScreenManager.AddScreenAndLoadContent(GameScreen screen) in GameScreens\ScreenManager.cs:line 146
   at ScreenManager.AddPendingScreens() in GameScreens\ScreenManager.cs:line 157
   at ScreenManager.Update(UpdateTimes elapsed) in GameScreens\ScreenManager.cs:line 679
   at GameBase.UpdateGame(Single deltaTime) in GameScreens\GameBase.cs:line 229
   at StarDriveGame.Update(Single deltaTime) in GameScreens\StarDriveGame.cs:line 142
   at XNA.Game.Tick() in ts\BlackBox\XNA.Game\Game.cs:line 250
   at XNA.Game.HostIdle(Object sender, EventArgs e) in ts\BlackBox\XNA.Game\Game.cs:line 488
   at XNA.GameHost.OnIdle() in ts\BlackBox\XNA.Game\GameHost.cs:line 55
   at XNA.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e) in ts\BlackBox\XNA.Game\WindowsGameHost.cs:line 73
   at XNA.WindowsGameHost.Run() in ts\BlackBox\XNA.Game\WindowsGameHost.cs:line 87
   at XNA.Game.Run() in ts\BlackBox\XNA.Game\Game.cs:line 157
   at Program.Main(String[] args) in GameScreens\Program.cs:line 217

**Comment by gkapulis** [comment]
No reproduction. Other saves worked well.
