### ISSUE TITLE
combined arms error

### ISSUE THREAD

**Issue by leondus** [TeamStarDrive/StarDrive#190]
(!) Exception: UpdateGame() failed

An item with the same key has already been added.
Version = 1.50.15000 mars-1.50
Mod = Combined Arms
ModVersion = v8.6e
Language = English
StarDate = NULL
Ships = NULL
Planets = NULL
Memory = 210644
XnaMemory = 145135
Thread = Main Thread
ThreadId = 1
Thread #1 Main Thread StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.System.Collections.IDictionary.Add(Object key, Object value)
   at Ship_Game.Data.Serialization.Types.MapSerializer.Deserialize(YamlNode node)
   at Ship_Game.Data.Serialization.DataField.SetDeserialized(Object instance, YamlNode node)
   at Ship_Game.Data.YamlSerializer.YamlSerializer.Deserialize(YamlNode node)
   at Ship_Game.Data.Yaml.YamlParser.DeserializeArray[T]()
   at Ship_Game.Data.Yaml.YamlParser.DeserializeArray[T](String modOrVanillaFile)
   at Ship_Game.AI.Components.BudgetPriorities.LoadBudgetSettings(Empire empire)
   at Ship_Game.AI.Components.BudgetPriorities..ctor(Empire empire)
   at Ship_Game.AI.EmpireAI.InitializeManagers(Empire e)
   at Ship_Game.AI.EmpireAI..ctor(Empire e)
   at Ship_Game.Empire.Initialize()
   at Ship_Game.GameScreens.NewGame.UniverseGenerator..ctor(UniverseParams p)
   at Ship_Game.CreatingNewGameScreen..ctor(MainMenuScreen menu, UniverseParams p)
   at Ship_Game.RaceDesignScreen.OnEngageClicked(UIButton b)
   at Ship_Game.UIButton.OnButtonClicked()
   at Ship_Game.UIButton.HandleInput(InputState input)
   at Ship_Game.UIElementContainer.HandleInput(InputState input)
   at Ship_Game.GameScreen.HandleInput(InputState input)
   at Ship_Game.RaceDesignScreen.HandleInput(InputState input)
   at Ship_Game.ScreenManager.Update(UpdateTimes elapsed)
   at Ship_Game.GameBase.UpdateGame(Single deltaTime)

**Comment by gkapulis** [comment]
Please update to latest patch and retry. 
check this vid for instructions: https://www.youtube.com/watch?v=emgWRMSpcMU
